### ISSUE TITLE
[EPIC] Create classes for etl

### ISSUE THREAD

**Issue by Poehavshi** [Poehavshi/Text2CarsGeneration#2]
I want to create baseline for dataset creation

- [x]  https://github.com/Poehavshi/Text2CarsGeneration/issues/4
- [x] Create meta information transform
- [x] https://github.com/Poehavshi/Text2CarsGeneration/issues/6
